[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "domsync"
authors = [{name = "Peter Divos", email = "pdivos@gmail.com"}]
dynamic = ["version", "description"]
